"""empty message

Revision ID: 3f721d002d70
Revises: None
Create Date: 2015-12-29 20:27:12.735678

"""

# revision identifiers, used by Alembic.
revision = '3f721d002d70'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activate_token', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('verified', sa.Boolean(name='verified'), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('second_name', sa.String(length=60), nullable=True),
    sa.Column('access', sa.String(length=1), nullable=True),
    sa.Column('chip_number', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('chip_number', name='uq_users_chip_number')
    )
    op.create_index('ix_users_access', 'users', ['access'], unique=False)
    op.create_index('ix_users_card_number', 'users', ['card_number'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_second_name', 'users', ['second_name'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=40), nullable=False),
    sa.Column('access_time_from', sa.Time(), nullable=True),
    sa.Column('access_time_to', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_groups')
    )
    op.create_index('ix_groups_access_time_from', 'groups', ['access_time_from'], unique=False)
    op.create_index('ix_groups_access_time_to', 'groups', ['access_time_to'], unique=False)
    op.create_index('ix_groups_group_name', 'groups', ['group_name'], unique=False)
    op.create_table('user_has_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_user_has_group_group_id_groups'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_has_group_user_id_users'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'group_id', name='pk_user_has_group')
    )
    op.create_table('user_password_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('used', sa.Boolean(name='used'), nullable=True),
    sa.Column('expiration_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_password_tokens_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_user_password_tokens')
    )
    op.create_index('ix_user_password_tokens_value', 'user_password_tokens', ['value'], unique=False)
    op.create_table('group_has_timecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('timecard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_group_has_timecard_group_id_groups'),
    sa.ForeignKeyConstraint(['timecard_id'], ['timecard.id'], name='fk_group_has_timecard_timecard_id_timecard'),
    sa.PrimaryKeyConstraint('id', 'group_id', 'timecard_id', name='pk_group_has_timecard')
    )
    op.add_column(u'carddata', sa.Column('access', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'carddata', 'access')
    op.drop_table('group_has_timecard')
    op.drop_index('ix_user_password_tokens_value', table_name='user_password_tokens')
    op.drop_table('user_password_tokens')
    op.drop_table('user_has_group')
    op.drop_index('ix_groups_group_name', table_name='groups')
    op.drop_index('ix_groups_access_time_to', table_name='groups')
    op.drop_index('ix_groups_access_time_from', table_name='groups')
    op.drop_table('groups')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_second_name', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_card_number', table_name='users')
    op.drop_index('ix_users_access', table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
